// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type TemplateChunk struct {
	ID          int64
	DocID       int64
	OffsetStart int64
	OffsetEnd   int64
	Text        string
}

type TemplateDocument struct {
	ID       int64
	Title    string
	Filename string
	UploadAt sql.NullTime
}
